import { Quest } from './types';

export const QUESTS: Quest[] = [
  {
		id: "section-1",
		number: 1,
		title: "Nền tảng Aiken",
		description: "Bắt đầu hành trình bằng cách thiết lập môi trường lập trình cục bộ với Aiken CLI. Bạn sẽ làm chủ cú pháp của một ngôn ngữ lập trình hàm hiện đại, học cách định nghĩa Custom Types (Kiểu dữ liệu tùy chỉnh) và điều khiển luồng dữ liệu (Control Flow). Cuối cùng, bạn sẽ sử dụng khung thử nghiệm (unit testing) tích hợp sẵn để đảm bảo logic của mình hoạt động hoàn hảo trước khi đưa lên mạng lưới!",
		imageAlt: "Nền tảng Aiken",
		colorTheme: "text-[#B6F2B6]",
		illustrationType: "token",
		link: "/docs/nen-tang-aiken",
  },
  {
		id: "section-2",
		number: 2,
		title: "Kiến trúc Cardano",
		description: "Sức mạnh đặc biệt của Cardano nằm ở kiến trúc eUTxO độc nhất. Bạn sẽ đi sâu vào mô hình lưu trữ để hiểu sự khác biệt của nó so với các blockchain dựa trên tài khoản (account-based). Sau đó, bạn sẽ khám phá cơ chế bí mật để truyền dữ liệu giữa các giao dịch thông qua Datum và Redeemers.",
		imageAlt: "Kiến trúc blockchain Cardano",
		colorTheme: "text-[#C6A8FF]",
		illustrationType: "staking",
		link: "/docs/kien-truc-cardano",
  },
  {
		id: "section-3",
		number: 3,
		title: "Validator đầu tiên",
		description: "Đã đến lúc viết Hợp đồng thông minh (Smart Contract) thực thụ đầu tiên! Bạn sẽ xây dựng một tập lệnh xác thực cơ bản nhằm tạo ra các quy tắc để khóa và mở khóa tài sản. Bạn cũng sẽ học cách biên dịch mã Aiken và triển khai logic để quyết định ai được quyền chi tiêu UTxO và ai bị từ chối.",
		imageAlt: "Validator thông minh đầu tiên",
		colorTheme: "text-[#FFD8A8]",
		illustrationType: "vendor",
		link: "/docs/validator-dau-tien",
  },
  {
		id: "section-4",
		number: 4,
		title: "Mint token & NFT",
		description: "Tự tạo đồng tiền riêng hoặc các tác phẩm nghệ thuật kỹ thuật số độc bản! Bạn sẽ viết các Chính sách đúc (Minting Policies) để quản lý vòng đời của các Tài sản bản địa (Native Assets). Cho dù đó là một nguồn cung token có thể thay thế hay một NFT duy nhất, bạn sẽ kiểm soát chính xác cách chúng được tạo ra và tiêu hủy trên mạng lưới để chia sẻ với bạn bè!",
		imageAlt: "Mint token và NFT",
		colorTheme: "text-[#FFF79A]",
		illustrationType: "nft",
		link: "/docs/mint-token-nft",
  },
  {
		id: "section-5",
		number: 5,
		title: "Hợp đồng Escrow",
		description: "Kết hợp tất cả kiến thức đã học vào một ứng dụng Trao đổi không cần sự tin tưởng (Trustless Exchange). Bạn sẽ xây dựng một hợp đồng Ký quỹ (Escrow) mạnh mẽ, nơi người mua, người bán và người trung gian tương tác với nhau. Bạn sẽ sử dụng kỹ thuật khớp mẫu (pattern matching) nâng cao để giữ tiền an toàn cho đến khi các điều kiện cụ thể được đáp ứng, đảm bảo giao dịch an toàn cho tất cả mọi người!",
		imageAlt: "Hợp đồng ký quỹ",
		colorTheme: "text-[#B6F2B6]",
		illustrationType: "lending",
		link: "/docs/hop-dong-escrow",
  },
];
