import { Quest } from './types';

export const QUESTS: Quest[] = [
  {
		id: "section-1",
		number: 1,
		title: "Nền tảng Aiken",
		description: "CLI, cú pháp, kiểu dữ liệu, kiểm thử.",
		imageAlt: "Nền tảng Aiken",
		colorTheme: "text-[#B6F2B6]",
		illustrationType: "token",
		link: "/docs/nen-tang-aiken",
  },
  {
		id: "section-2",
		number: 2,
		title: "Kiến trúc Cardano",
		description: "Kiến trúc eUTxO, Datum và Redeemer.",
		imageAlt: "Kiến trúc blockchain Cardano",
		colorTheme: "text-[#C6A8FF]",
		illustrationType: "staking",
		link: "/docs/kien-truc-cardano",
  },
  {
		id: "section-3",
		number: 3,
		title: "Validator đầu tiên",
		description: "Viết và kiểm thử validator chi tiêu đầu tay.",
		imageAlt: "Validator thông minh đầu tiên",
		colorTheme: "text-[#FFD8A8]",
		illustrationType: "vendor",
		link: "/docs/validator-dau-tien",
  },
  {
		id: "section-4",
		number: 4,
		title: "Mint token & NFT",
		description: "Tạo token gốc và NFT trên Cardano.",
		imageAlt: "Mint token và NFT",
		colorTheme: "text-[#FFF79A]",
		illustrationType: "nft",
		link: "/docs/mint-token-nft",
  },
  {
		id: "section-5",
		number: 5,
		title: "Hợp đồng Escrow",
		description: "Xây ứng dụng ký quỹ không cần tin cậy.",
		imageAlt: "Hợp đồng ký quỹ",
		colorTheme: "text-[#B6F2B6]",
		illustrationType: "lending",
		link: "/docs/hop-dong-escrow",
  },
];
